"""Add address to profiles and increase brief_history length

Revision ID: 083385ec9c4b
Revises: 1e3512d8a2cf
Create Date: 2026-03-04 22:20:19.908318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083385ec9c4b'
down_revision: Union[str, Sequence[str], None] = '1e3512d8a2cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('medical_records', 'brief_history',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1500),
               existing_nullable=True)
    op.add_column('patient_profiles', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'address')
    op.alter_column('medical_records', 'brief_history',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.drop_column('doctor_profiles', 'address')
    # ### end Alembic commands ###
