"""add_allergies_conditions_remove_prev_dx

Revision ID: 08cf2cb52227
Revises: e32d94aefbf8
Create Date: 2026-01-06 23:34:51.629909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08cf2cb52227'
down_revision: Union[str, Sequence[str], None] = 'e32d94aefbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MEDICATION', 'FOOD', 'SUBSTANCE', 'OTHER', name='allergytype'), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', 'UNKNOWN', name='allergyseverity'), nullable=False),
    sa.Column('source', sa.Enum('DOCTOR', 'SUSPECTED', 'NOT_SURE', name='allergysource'), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', name='allergystatus'), nullable=False),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_id'), 'allergies', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('since_year', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CONTROLLED', 'RESOLVED', 'UNKNOWN', name='conditionstatus'), nullable=False),
    sa.Column('source', sa.Enum('DOCTOR', 'SUSPECTED', name='conditionsource'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.drop_column('patient_profiles', 'previous_diagnoses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('previous_diagnoses', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_allergies_id'), table_name='allergies')
    op.drop_table('allergies')
    # ### end Alembic commands ###
