"""Add health habits and family history tables

Revision ID: 1e3512d8a2cf
Revises: a19bbc68568c
Create Date: 2026-03-04 21:05:10.861049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3512d8a2cf'
down_revision: Union[str, Sequence[str], None] = 'a19bbc68568c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_history_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('family_members', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_history_conditions_id'), 'family_history_conditions', ['id'], unique=False)
    op.create_table('health_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('tobacco_use', sa.Enum('NEVER', 'EX_SMOKER', 'OCCASIONAL', 'ACTIVE', name='tobaccouse'), nullable=True),
    sa.Column('cigarettes_per_day', sa.Integer(), nullable=True),
    sa.Column('years_smoking', sa.Integer(), nullable=True),
    sa.Column('years_since_quit', sa.Integer(), nullable=True),
    sa.Column('alcohol_use', sa.Enum('NONE', 'OCCASIONAL', 'SOCIAL', 'FREQUENT', name='alcoholuse'), nullable=True),
    sa.Column('drinks_per_week', sa.Integer(), nullable=True),
    sa.Column('drug_use', sa.Boolean(), nullable=True),
    sa.Column('drug_type', sa.String(), nullable=True),
    sa.Column('drug_frequency', sa.String(), nullable=True),
    sa.Column('physical_activity', sa.Enum('SEDENTARY', 'ONE_TWO', 'THREE_FOUR', 'FIVE_PLUS', name='physicalactivity'), nullable=True),
    sa.Column('diet', sa.Enum('BALANCED', 'HIGH_CARB', 'HIGH_FAT', 'VEGETARIAN', 'VEGAN', 'OTHER', name='diettype'), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_problems', sa.Boolean(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_profile_id')
    )
    op.create_index(op.f('ix_health_habits_id'), 'health_habits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_habits_id'), table_name='health_habits')
    op.drop_table('health_habits')
    op.drop_index(op.f('ix_family_history_conditions_id'), table_name='family_history_conditions')
    op.drop_table('family_history_conditions')
    # ### end Alembic commands ###
