"""add_family_invitations_table

Revision ID: 27dbd41af3bb
Revises: fa2e9ace06c7
Create Date: 2026-05-18 21:41:48.685817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dbd41af3bb'
down_revision: Union[str, Sequence[str], None] = 'fa2e9ace06c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('relationship_type', sa.Enum('SELF', 'PARENT', 'CHILD', 'SPOUSE', 'SIBLING', 'GRANDPARENT', 'GRANDCHILD', 'GUARDIAN', 'OTHER', name='familyrelationshiptype'), nullable=False),
    sa.Column('access_level', sa.Enum('FULL_ACCESS', 'READ_ONLY', 'EMERGENCY_ONLY', name='familyaccesslevel'), nullable=False),
    sa.Column('can_manage_family', sa.Boolean(), nullable=False),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_invitations')
    # ### end Alembic commands ###
