"""add_sex_city_country_to_patient_profiles

Revision ID: 52268740320e
Revises: 27dbd41af3bb
Create Date: 2026-05-18 22:44:34.514579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52268740320e'
down_revision: Union[str, Sequence[str], None] = '27dbd41af3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('patient_profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'country')
    op.drop_column('patient_profiles', 'city')
    op.drop_column('patient_profiles', 'sex')
    # ### end Alembic commands ###
