"""add_record_view_logs

Revision ID: 55ad7d03b2e1
Revises: c8a3e5f1d7b2
Create Date: 2026-03-14 03:24:11.524953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ad7d03b2e1'
down_revision: Union[str, Sequence[str], None] = 'c8a3e5f1d7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_view_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_view_logs_doctor_id'), 'record_view_logs', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_record_view_logs_medical_record_id'), 'record_view_logs', ['medical_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_view_logs_medical_record_id'), table_name='record_view_logs')
    op.drop_index(op.f('ix_record_view_logs_doctor_id'), table_name='record_view_logs')
    op.drop_table('record_view_logs')
    # ### end Alembic commands ###
