"""add_doctor_created_patient_fields

Revision ID: 648ad44c466b
Revises: a61662168ede
Create Date: 2026-03-24 22:37:16.200961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648ad44c466b'
down_revision: Union[str, Sequence[str], None] = 'a61662168ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_claim_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='claimstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_claim_requests_patient_profile_id'), 'profile_claim_requests', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_profile_claim_requests_user_id'), 'profile_claim_requests', ['user_id'], unique=False)
    op.add_column('patient_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('created_by_doctor_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_patient_profiles_email'), 'patient_profiles', ['email'], unique=False)
    op.create_foreign_key(None, 'patient_profiles', 'users', ['created_by_doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_patient_profiles_email'), table_name='patient_profiles')
    op.drop_column('patient_profiles', 'created_by_doctor_id')
    op.drop_column('patient_profiles', 'email')
    op.drop_index(op.f('ix_profile_claim_requests_user_id'), table_name='profile_claim_requests')
    op.drop_index(op.f('ix_profile_claim_requests_patient_profile_id'), table_name='profile_claim_requests')
    op.drop_table('profile_claim_requests')
    # ### end Alembic commands ###
