"""rename_title_to_motive

Revision ID: 91b2f40caa19
Revises: bb13e581db0e
Create Date: 2026-01-07 23:50:05.839102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b2f40caa19'
down_revision: Union[str, Sequence[str], None] = 'bb13e581db0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records', 'title', new_column_name='motive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_records', 'motive', new_column_name='title')
    # ### end Alembic commands ###
