"""add_verification_fields_to_allergies_and_conditions

Revision ID: 9af548ace5f4
Revises: e2a07daa490f
Create Date: 2026-01-20 19:19:00.829694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af548ace5f4'
down_revision: Union[str, Sequence[str], None] = 'e2a07daa490f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergies', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('allergies', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'allergies', 'users', ['verified_by'], ['id'])
    op.add_column('conditions', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('conditions', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'conditions', 'users', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conditions', type_='foreignkey')
    op.drop_column('conditions', 'verified_at')
    op.drop_column('conditions', 'verified_by')
    op.drop_constraint(None, 'allergies', type_='foreignkey')
    op.drop_column('allergies', 'verified_at')
    op.drop_column('allergies', 'verified_by')
    # ### end Alembic commands ###
