"""add_tags_to_medical_record

Revision ID: 9e448389bcc8
Revises: 91b2f40caa19
Create Date: 2026-01-07 23:58:28.718854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e448389bcc8'
down_revision: Union[str, Sequence[str], None] = '91b2f40caa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'tags')
    # ### end Alembic commands ###
