"""Add sex field to users table

Revision ID: a1fa027c64bb
Revises: d258b29121e2
Create Date: 2026-02-04 17:31:25.652369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1fa027c64bb'
down_revision: Union[str, Sequence[str], None] = 'd258b29121e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create sex enum type
    sex_enum = sa.Enum('MASCULINO', 'FEMININO', name='sex')
    sex_enum.create(op.get_bind(), checkfirst=True)
    
    # Add sex column to users table
    op.add_column('users', sa.Column('sex', sex_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    # Drop sex enum type
    sa.Enum(name='sex').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
