"""enhance_medication_model_with_fhir_fields

Revision ID: b5eb77ef0b1d
Revises: 2f3c4d5e6f7a
Create Date: 2026-01-27 15:06:26.570375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5eb77ef0b1d'
down_revision: Union[str, Sequence[str], None] = '2f3c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Add FHIR-compliant fields to medications table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add enum types for medication status and source
    medication_status_enum = postgresql.ENUM('ACTIVE', 'COMPLETED', 'STOPPED', 'ON_HOLD', 'ENTERED_IN_ERROR', 'NOT_TAKEN', name='medicationstatus')
    medication_status_enum.create(op.get_bind(), checkfirst=True)
    
    medication_source_enum = postgresql.ENUM('PRESCRIBED', 'OTC', 'SELF_REPORTED', 'TRANSFERRED', name='medicationsource')
    medication_source_enum.create(op.get_bind(), checkfirst=True)
    
    # Step 2: Add new columns (nullable first for existing data)
    op.add_column('medications', sa.Column('status', postgresql.ENUM('ACTIVE', 'COMPLETED', 'STOPPED', 'ON_HOLD', 'ENTERED_IN_ERROR', 'NOT_TAKEN', name='medicationstatus', create_type=False), nullable=True))
    op.add_column('medications', sa.Column('status_reason', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('medications', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('medications', sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('medications', sa.Column('source', postgresql.ENUM('PRESCRIBED', 'OTC', 'SELF_REPORTED', 'TRANSFERRED', name='medicationsource', create_type=False), nullable=True))
    op.add_column('medications', sa.Column('prescribed_by_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('medications', sa.Column('external_prescriber_name', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('condition_id', sa.Integer(), nullable=True))
    op.add_column('medications', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('medications', sa.Column('created_by_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('medications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Step 3: Migrate existing data - set defaults for existing records
    op.execute("""
        UPDATE medications 
        SET 
            status = 'ACTIVE',
            source = 'SELF_REPORTED',
            recorded_at = COALESCE(recorded_at, NOW()),
            created_by_id = patient_profile_id  -- Temporary: use patient_profile_id as created_by
        WHERE status IS NULL
    """)
    
    # Step 4: Update patient_profile_id to match user_id where possible
    op.execute("""
        UPDATE medications m
        SET created_by_id = pp.user_id
        FROM patient_profiles pp
        WHERE m.patient_profile_id = pp.id 
        AND pp.user_id IS NOT NULL
        AND m.created_by_id = m.patient_profile_id
    """)
    
    # Step 5: Make columns non-nullable after setting defaults
    op.alter_column('medications', 'status', nullable=False)
    op.alter_column('medications', 'source', nullable=False)
    op.alter_column('medications', 'recorded_at', nullable=False)
    op.alter_column('medications', 'created_by_id', nullable=False)
    
    # Step 6: Make dosage and frequency nullable (more flexible)
    op.alter_column('medications', 'dosage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('medications', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Step 7: Create foreign keys
    op.create_foreign_key('fk_medications_created_by', 'medications', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_medications_prescribed_by', 'medications', 'users', ['prescribed_by_id'], ['id'])
    op.create_foreign_key('fk_medications_condition', 'medications', 'conditions', ['condition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Remove FHIR fields from medications table."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign keys
    op.drop_constraint('fk_medications_condition', 'medications', type_='foreignkey')
    op.drop_constraint('fk_medications_prescribed_by', 'medications', type_='foreignkey')
    op.drop_constraint('fk_medications_created_by', 'medications', type_='foreignkey')
    
    # Make dosage and frequency non-nullable again
    op.alter_column('medications', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('medications', 'dosage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # Drop new columns
    op.drop_column('medications', 'updated_at')
    op.drop_column('medications', 'created_by_id')
    op.drop_column('medications', 'notes')
    op.drop_column('medications', 'instructions')
    op.drop_column('medications', 'condition_id')
    op.drop_column('medications', 'external_prescriber_name')
    op.drop_column('medications', 'prescribed_by_id')
    op.drop_column('medications', 'source')
    op.drop_column('medications', 'recorded_at')
    op.drop_column('medications', 'end_date')
    op.drop_column('medications', 'start_date')
    op.drop_column('medications', 'status_reason')
    op.drop_column('medications', 'status')
    
    # Drop enum types
    postgresql.ENUM(name='medicationsource').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='medicationstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
