"""add_vital_signs_status_and_audit

Revision ID: c958b9264804
Revises: 55ad7d03b2e1
Create Date: 2026-03-16 18:44:44.317735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c958b9264804'
down_revision: Union[str, Sequence[str], None] = '55ad7d03b2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first (idempotent)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE vitalsignsstatus AS ENUM ('UNVERIFIED', 'VERIFIED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.add_column('vital_signs', sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', name='vitalsignsstatus', create_type=False), server_default='UNVERIFIED', nullable=False))
    op.add_column('vital_signs', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('vital_signs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'vital_signs', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vital_signs', type_='foreignkey')
    op.drop_column('vital_signs', 'updated_at')
    op.drop_column('vital_signs', 'updated_by')
    op.drop_column('vital_signs', 'status')
    # ### end Alembic commands ###
