"""add_code_fields_and_soft_delete_to_allergies_conditions

Revision ID: cb6deb94c321
Revises: 9e448389bcc8
Create Date: 2026-01-20 15:32:17.998561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'cb6deb94c321'
down_revision: Union[str, Sequence[str], None] = '9e448389bcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add nullable columns first for FHIR code fields
    op.add_column('allergies', sa.Column('code', sa.String(), nullable=True))
    op.add_column('allergies', sa.Column('code_system', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('code', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('code_system', sa.String(), nullable=True))
    
    # Add created_at as nullable first, set default for existing rows, then make NOT NULL
    op.add_column('allergies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('conditions', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Update existing rows with current timestamp
    op.execute(text("UPDATE allergies SET created_at = NOW() WHERE created_at IS NULL"))
    op.execute(text("UPDATE conditions SET created_at = NOW() WHERE created_at IS NULL"))
    
    # Now make created_at NOT NULL
    op.alter_column('allergies', 'created_at', nullable=False)
    op.alter_column('conditions', 'created_at', nullable=False)
    
    # Add deleted as nullable first, set default, then make NOT NULL
    op.add_column('allergies', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('conditions', sa.Column('deleted', sa.Boolean(), nullable=True))
    
    # Update existing rows with False
    op.execute(text("UPDATE allergies SET deleted = FALSE WHERE deleted IS NULL"))
    op.execute(text("UPDATE conditions SET deleted = FALSE WHERE deleted IS NULL"))
    
    # Now make deleted NOT NULL
    op.alter_column('allergies', 'deleted', nullable=False)
    op.alter_column('conditions', 'deleted', nullable=False)
    
    # Add deleted_at (this can be NULL)
    op.add_column('allergies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('conditions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'deleted_at')
    op.drop_column('conditions', 'deleted')
    op.drop_column('conditions', 'created_at')
    op.drop_column('conditions', 'code_system')
    op.drop_column('conditions', 'code')
    op.drop_column('allergies', 'deleted_at')
    op.drop_column('allergies', 'deleted')
    op.drop_column('allergies', 'created_at')
    op.drop_column('allergies', 'code_system')
    op.drop_column('allergies', 'code')
    # ### end Alembic commands ###
