"""Add has_diagnosis and order fields to Category

Revision ID: d258b29121e2
Revises: d0cf63b5b367
Create Date: 2026-02-04 15:19:11.338417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd258b29121e2'
down_revision: Union[str, Sequence[str], None] = 'd0cf63b5b367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('has_diagnosis', sa.Boolean(), nullable=True))
    op.add_column('categories', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'order')
    op.drop_column('categories', 'has_diagnosis')
    # ### end Alembic commands ###
