"""add_diagnosis_codes_status_and_audit_fields_to_medical_records

Revision ID: e2a07daa490f
Revises: ef2baf9dc456
Create Date: 2026-01-20 18:44:11.784671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'e2a07daa490f'
down_revision: Union[str, Sequence[str], None] = 'ef2baf9dc456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add nullable columns first
    op.add_column('medical_records', sa.Column('diagnosis_code', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('diagnosis_code_system', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('medical_records', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    
    # Add status as nullable first
    op.execute("CREATE TYPE recordstatus AS ENUM ('UNVERIFIED', 'BACKED_BY_DOCUMENT', 'VERIFIED')")
    op.add_column('medical_records', sa.Column('status', sa.Enum('UNVERIFIED', 'BACKED_BY_DOCUMENT', 'VERIFIED', name='recordstatus'), nullable=True))
    
    # Add created_by as nullable first  
    op.add_column('medical_records', sa.Column('created_by', sa.Integer(), nullable=True))
    
    # For existing records, we need to set a default created_by
    # Get the patient_id's user_id as the creator (the patient created their own record)
    op.execute(text("""
        UPDATE medical_records mr
        SET created_by = pp.user_id,
            status = 'UNVERIFIED'
        FROM patient_profiles pp
        WHERE mr.patient_id = pp.id AND mr.created_by IS NULL
    """))
    
    # Now make created_by and status NOT NULL
    op.alter_column('medical_records', 'created_by', nullable=False)
    op.alter_column('medical_records', 'status', nullable=False)
    
    # Create foreign keys
    op.create_foreign_key('fk_medical_records_verified_by', 'medical_records', 'users', ['verified_by'], ['id'])
    op.create_foreign_key('fk_medical_records_created_by', 'medical_records', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_medical_records_created_by', 'medical_records', type_='foreignkey')
    op.drop_constraint('fk_medical_records_verified_by', 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'verified_at')
    op.drop_column('medical_records', 'verified_by')
    op.drop_column('medical_records', 'created_by')
    op.drop_column('medical_records', 'status')
    op.execute("DROP TYPE recordstatus")
    op.drop_column('medical_records', 'diagnosis_code_system')
    op.drop_column('medical_records', 'diagnosis_code')
    # ### end Alembic commands ###
