"""make_code_and_code_system_not_nullable

Revision ID: ef2baf9dc456
Revises: cb6deb94c321
Create Date: 2026-01-20 15:41:29.395783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2baf9dc456'
down_revision: Union[str, Sequence[str], None] = 'cb6deb94c321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allergies', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('allergies', 'code_system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conditions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conditions', 'code_system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conditions', 'code_system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conditions', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('allergies', 'code_system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('allergies', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
