"""initial_schema

Revision ID: f446816df8ed
Revises: 
Create Date: 2026-02-10 22:51:15.344222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f446816df8ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('has_diagnosis', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('health_centers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('HOSPITAL', 'CLINIC', 'PRIVATE_PRACTICE', 'LAB', 'OTHER', name='healthcentertype'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_centers_name'), 'health_centers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DOCTOR', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('sex', sa.Enum('MASCULINO', 'FEMENINO', name='sex'), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('short_bio', sa.Text(), nullable=True),
    sa.Column('workplaces', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('health_center_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('health_center_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'DOCTOR', 'STAFF', name='healthcenterrole'), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['health_center_id'], ['health_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_center_memberships_health_center_id'), 'health_center_memberships', ['health_center_id'], unique=False)
    op.create_index(op.f('ix_health_center_memberships_user_id'), 'health_center_memberships', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('access_level', sa.Enum('READ_ONLY', 'WRITE', name='doctoraccesslevel'), nullable=False),
    sa.Column('access_type', sa.Enum('PERMANENT', 'TEMPORARY', name='accesstype'), nullable=False),
    sa.Column('expires_in_days', sa.Integer(), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_invitations_code'), 'access_invitations', ['code'], unique=True)
    op.create_index(op.f('ix_access_invitations_patient_profile_id'), 'access_invitations', ['patient_profile_id'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('code_system', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MEDICATION', 'FOOD', 'SUBSTANCE', 'OTHER', name='allergytype'), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', 'UNKNOWN', name='allergyseverity'), nullable=False),
    sa.Column('source', sa.Enum('DOCTOR', 'SUSPECTED', 'NOT_SURE', name='allergysource'), nullable=False),
    sa.Column('status', sa.Enum('UNVERIFIED', 'VERIFIED', name='allergystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_id'), 'allergies', ['id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('code_system', sa.String(), nullable=False),
    sa.Column('since_year', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CONTROLLED', 'RESOLVED', 'UNKNOWN', name='conditionstatus'), nullable=False),
    sa.Column('source', sa.Enum('DOCTOR', 'SUSPECTED', name='conditionsource'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_table('doctor_patient_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('patient_profile_id', sa.UUID(), nullable=True),
    sa.Column('access_type', sa.Enum('PERMANENT', 'TEMPORARY', name='accesstype'), nullable=False),
    sa.Column('access_level', sa.Enum('READ_ONLY', 'WRITE', name='doctoraccesslevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_patient_access_doctor_id'), 'doctor_patient_access', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_patient_access_patient_profile_id'), 'doctor_patient_access', ['patient_profile_id'], unique=False)
    op.create_table('family_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('SELF', 'PARENT', 'CHILD', 'SPOUSE', 'SIBLING', 'GRANDPARENT', 'GRANDCHILD', 'GUARDIAN', 'OTHER', name='relationshiptype'), nullable=False),
    sa.Column('access_level', sa.Enum('FULL_ACCESS', 'READ_ONLY', 'EMERGENCY_ONLY', name='accesslevel'), nullable=False),
    sa.Column('can_manage_family', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_membership', 'family_memberships', ['user_id', 'patient_profile_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_family_memberships_patient_profile_id'), 'family_memberships', ['patient_profile_id'], unique=False)
    op.create_index(op.f('ix_family_memberships_user_id'), 'family_memberships', ['user_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('motive', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('record_source', sa.Enum('PATIENT', 'DOCTOR', 'IMPORTED', name='recordsource'), nullable=False),
    sa.Column('brief_history', sa.String(length=300), nullable=True),
    sa.Column('has_red_flags', sa.Boolean(), nullable=True),
    sa.Column('red_flags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('key_finding', sa.String(length=250), nullable=True),
    sa.Column('clinical_impression', sa.Text(), nullable=True),
    sa.Column('actions_today', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('plan_bullets', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('follow_up_interval', sa.String(length=50), nullable=True),
    sa.Column('follow_up_with', sa.String(length=200), nullable=True),
    sa.Column('patient_instructions', sa.String(length=350), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'BACKED_BY_DOCUMENT', 'VERIFIED', name='recordstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('share_type', sa.Enum('SPECIFIC_RECORDS', 'SUMMARY', name='sharetype', native_enum=False, length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('is_single_use', sa.Boolean(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_tokens_token'), 'share_tokens', ['token'], unique=True)
    op.create_table('clinical_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('LAB', 'IMAGING', 'REFERRAL', 'PROCEDURE', name='ordertype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('urgency', sa.Enum('ROUTINE', 'URGENT', 'STAT', name='orderurgency'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('referral_to', sa.String(length=200), nullable=True),
    sa.Column('is_doctor_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_orders_medical_record_id'), 'clinical_orders', ['medical_record_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('diagnosis_code', sa.String(), nullable=True),
    sa.Column('diagnosis_code_system', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'PROVISIONAL', 'DIFFERENTIAL', 'REFUTED', 'ENTERED_IN_ERROR', name='diagnosisstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'STOPPED', 'ON_HOLD', 'ENTERED_IN_ERROR', 'NOT_TAKEN', name='medicationstatus'), nullable=False),
    sa.Column('status_reason', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Enum('PRESCRIBED', 'OTC', 'SELF_REPORTED', 'TRANSFERRED', name='medicationsource'), nullable=False),
    sa.Column('prescribed_by_id', sa.UUID(), nullable=True),
    sa.Column('external_prescriber_name', sa.String(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('share_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_token_id', sa.UUID(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['share_token_id'], ['share_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_access_logs_share_token_id'), 'share_access_logs', ['share_token_id'], unique=False)
    op.create_table('shared_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_token_id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_token_id'], ['share_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_records_medical_record_id'), 'shared_records', ['medical_record_id'], unique=False)
    op.create_index(op.f('ix_shared_records_share_token_id'), 'shared_records', ['share_token_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_id', sa.UUID(), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('is_doctor_only', sa.Boolean(), nullable=False),
    sa.Column('linked_medication_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['linked_medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_medical_record_id'), 'prescriptions', ['medical_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_medical_record_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_shared_records_share_token_id'), table_name='shared_records')
    op.drop_index(op.f('ix_shared_records_medical_record_id'), table_name='shared_records')
    op.drop_table('shared_records')
    op.drop_index(op.f('ix_share_access_logs_share_token_id'), table_name='share_access_logs')
    op.drop_table('share_access_logs')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_table('medical_diagnoses')
    op.drop_table('documents')
    op.drop_index(op.f('ix_clinical_orders_medical_record_id'), table_name='clinical_orders')
    op.drop_table('clinical_orders')
    op.drop_index(op.f('ix_share_tokens_token'), table_name='share_tokens')
    op.drop_table('share_tokens')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_family_memberships_user_id'), table_name='family_memberships')
    op.drop_index(op.f('ix_family_memberships_patient_profile_id'), table_name='family_memberships')
    op.drop_index('ix_active_membership', table_name='family_memberships', postgresql_where=sa.text('is_active = true'))
    op.drop_table('family_memberships')
    op.drop_index(op.f('ix_doctor_patient_access_patient_profile_id'), table_name='doctor_patient_access')
    op.drop_index(op.f('ix_doctor_patient_access_doctor_id'), table_name='doctor_patient_access')
    op.drop_table('doctor_patient_access')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_allergies_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_access_invitations_patient_profile_id'), table_name='access_invitations')
    op.drop_index(op.f('ix_access_invitations_code'), table_name='access_invitations')
    op.drop_table('access_invitations')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_health_center_memberships_user_id'), table_name='health_center_memberships')
    op.drop_index(op.f('ix_health_center_memberships_health_center_id'), table_name='health_center_memberships')
    op.drop_table('health_center_memberships')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_health_centers_name'), table_name='health_centers')
    op.drop_table('health_centers')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
