"""add_profile_color_to_family_memberships

Revision ID: fa2e9ace06c7
Revises: f3b5d7e9a1c2
Create Date: 2026-05-18 21:37:44.403955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2e9ace06c7'
down_revision: Union[str, Sequence[str], None] = 'f3b5d7e9a1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_memberships', sa.Column('profile_color', sa.String(length=7), nullable=True))
    op.drop_index(op.f('ix_vital_signs_medical_record_id'), table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_patient_id'), table_name='vital_signs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vital_signs_patient_id'), 'vital_signs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vital_signs_medical_record_id'), 'vital_signs', ['medical_record_id'], unique=False)
    op.drop_column('family_memberships', 'profile_color')
    # ### end Alembic commands ###
